pull_request_rules:
  - name: Automatic merge into master if checks pass.
    conditions:
      - base=master
# Got annoyed with this.
#      - label=automerge
    actions:
      merge:
        method: merge
