steps:
  # ====================
  # Install Dependencies
  # ====================
  - id: "install-dependencies"
    name: node
    entrypoint: npm
    args: ["install", "--no-audit"]
    waitFor: ["-"] # The "-" indicates that this step begins immediately.
  # ====================
  # Build HTML + CSS Files
  # ====================
  - id: "build"
    name: node
    entrypoint: npm
    args: ["run", "build"]
    waitFor: ["install-dependencies"]
  # ====================
  # Test Site
  # ====================
  - id: "test"
    name: "armno/node-chromium"
    entrypoint: npm
    args: ["test"]
    waitFor: ["build"]
artifacts:
  objects:
    location: 'gs://anderson-an9304-build/$BRANCH_NAME/$SHORT_SHA'
    paths: ['_build/_testresult*']
