steps:
  # ====================
  # Install Dependencies
  # ====================
  - id: "install-dependencies"
    name: "eu.gcr.io/anderson-an9304/node-chromium" # See Dockerfile
    entrypoint: npm
    args: ["install", "--no-audit"]
    waitFor: ["-"] # The "-" indicates that this step begins immediately.
  # ====================
  # Build HTML + CSS Files
  # ====================
  - id: "build"
    name: "eu.gcr.io/anderson-an9304/node-chromium" # See Dockerfile
    entrypoint: npm
    args: ["run", "build"]
    waitFor: ["install-dependencies"]
  # ====================
  # Test Site
  # ====================
  - id: "test"
    name: "eu.gcr.io/anderson-an9304/node-chromium" # See Dockerfile
    entrypoint: npm
    args: ["test"]
    waitFor: ["build"]
  # ====================
  # Deploy Site
  # ====================
  - id: "deploy"
    name: "eu.gcr.io/anderson-an9304/firebase" # See Dockerfile
    args: ['deploy', '--project=anderson-an9304', '--only=hosting:$_ENVIRONMENT']
    waitFor: ["test"]

# ====================
# Save Test Results
# ====================
artifacts:
  objects:
    location: 'gs://anderson-an9304-build/$BRANCH_NAME/$SHORT_SHA'
    paths: ['_build/_testresult*']
